### PR TITLE
New ident

### PR DESCRIPTION
**Pull request by davidlatwe**
### New project logo type and splash screen :shipit: 

This PR is a follow-up to getavalon/core#138

new_ident

### CODE REVIEW

**Review by tokejepsen — APPROVED** [review]

**Comment by tokejepsen** [comment]
Actually should these icons not live in core?

**Comment by davidlatwe** [comment]
Ah yes, that should be a better place. (This did mention in getavalon/core#138, I forgot that :P)
If that's bee case, should we drop the original icon (remove the `/res/icon` folder) ?

main

**Comment by tokejepsen** [comment]
> If that's bee case, should we drop the original icon (remove the /res/icon folder) 

Yeah, a tidy would be good :)

**Review by BigRoy — APPROVED** [review]

**Comment by davidlatwe** [comment]
Can we merge this ? :smiley:

**Comment by mottosso** [comment]
Added you as collaborator, welcome to merge!

**Pull request merged**
