### PR TITLE
Big interface update

### PR DESCRIPTION
**Pull request by BigRoy**
### Feature changes

- Implement support for Actions (this will need an up-to-date core)
- Support assigned task per assets (a list of tasks can be set in asset's data, possible through project manager in core)
- Remains in system tray when closing (and reopens at same position where closed during that session)
- Implemented some catching of errors to avoid crashes if odd cases occur
- [Added `register_config_action` support](https://github.com/getavalon/launcher/commit/1ba5f2ead2ddeb800630288d29fcab719bd85027).
- Sorts projects and silos by name.

Some screenshots:

**Actions on any level**
afbeelding

**Actions on task level**
afbeelding

### CODE REVIEW

**Comment by BigRoy** [comment]
Please double check the functionality on your end since it's quite a big PR.

**Comment by tokejepsen** [comment]
> Implement support for Actions (this will need an up-to-date core)

Do you mean the latest commit on https://github.com/getavalon/core or does it require a PR?

Seems to work fine here with the latest commit.

**Comment by tokejepsen** [comment]
Maybe we should also update the README to reflect this UI change?

I'm going to document actions later when implementing them in https://github.com/getavalon/docker. Guessing https://github.com/getavalon/docs are the best place for this?

**Comment by BigRoy** [comment]
> Maybe we should also update the README to reflect this UI change?

Yes, that would be nice to have a new GIF there that shows it! I'm unfortunately short on time this week but feel free to push to this PR.

**Comment by BigRoy** [comment]
> Do you mean the latest commit on https://github.com/getavalon/core or does it require a PR?

I wasn't sure whether it would need the Colorbleed version of core - if it works on the current Avalon core that's perfect! Was hoping it would. Great.

**Comment by tokejepsen** [comment]
> Yes, that would be nice to have a new GIF there that shows it! I'm unfortunately short on time this week but feel free to push to this PR.

Posting this here before linking to it in a PR.

jul 4 2018 11_28 am

**Comment by BigRoy** [comment]
Lovely, thanks!!

**Comment by tokejepsen** [comment]
Think we are ready for a merge. Personally I can't press the button.

**Comment by BigRoy** [comment]
We might need to tag @mottosso for that!

**Comment by mottosso** [comment]
Happy to merge this, also added @tokejepsen to the collaborators list so you can merge as well!

**Comment by tokejepsen** [comment]
Eeek, going to press the button on this biggie!

**Pull request merged**
