### PR TITLE
Available for newer PyQt

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
- renaming of `icon` variable makes possible to run launcher with newer PyQt
- PyQt is printing warnings for `AwesomeIcon` with recommending but it's not crashing

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks @iLLiCiTiT, this looks good. Can you increment the version too? `1.0.1` should do, since it's a bugfix.

**Comment by iLLiCiTiT** [comment]
To make sure, in version.py change VERSION_PATCH to 1?

**Comment by mottosso** [comment]
Yes, sorry. That's the one!

**Comment by mottosso** [comment]
Great, thank you!

**Pull request merged**
