### PR TITLE
Fix asset task view

### PR DESCRIPTION
**Pull request by jasperges**
As discussed on [Gitter](https://gitter.im/getavalon/Lobby?at=5d3ab0c7a0a9760d34a0dd49) this makes only specific asset tasks show up in the Launcher.
This makes it consistent with the Project Launcher changes in [this PR](https://github.com/getavalon/core/pull/403).

### CODE REVIEW

**Comment by BigRoy** [comment]
Looks good to me. 

### Backwards incompatible behavior

However it's good to keep in mind that **with this change** any asset that has **NO** task assigned whatsoever cannot be entered and worked in anymore. You will always need to assign tasks before one could work in it.

As such project config tasks are just configured defaults for those tasks that one can create, not for the default lists for assets that have no tasks.

For projects where one previously worked inside a task that had no explicit tasks assigned one now first will need to assign the task before one is able to continue working on it. There's no database data about whether one worked in the task before, as such this also could not be accompanied with a simple "update"/"fix" script.

---

Tagging some people who might be interested in chiming in regarding this topic: @tokejepsen @davidlatwe 

If it's a problem we might need to put this "new behavior" behind a specific environment variable for to enable the new behavior as the new default behavior instead of breaking a potential pipeline in production.

**Comment by jasperges** [comment]
`AVALON_EARLY_ADOPTER`? And then probably first make `cbloader` etc. default. :smile: 

Another option would be tag the current version and do a release. Then after that do the update, tag again and do another release. And in the changelog clearly state that there is a backwards incompatible change.

**Comment by BigRoy** [comment]
> Another option would be tag the current version and do a release. Then after that do the update, tag again and do another release. And in the changelog clearly state that there is a backwards incompatible change.

@mottosso originally set the goal to be as backwards compatible as possible. In this case it's not breaking anything heavily so I'm fine with doing the tag and release. But I'll have @mottosso giving a verdict if he has the time.

**Comment by mottosso** [comment]
Yes, don't break backwards compatibility. Upgrading should be swift and painless, without surprises. The early adopter flag is a way for breaking change to happen to those that are aware of it happening, by explicitly setting that flag. If its possible to use that flag, then that would be good.

> You will always need to assign tasks before one could work in it.

I'm not well enough versed into what this change really does, but could there not be a default task for assets without one?

**Comment by jasperges** [comment]
Using the early adopter flag would be simple enough.

> I'm not well enough versed into what this change really does, but could there not be a default task for assets without one?

Adding a default task, would of course also be possible. But for us it makes sense to have assets (a sequence for example) **without any task**. Adding a default task also makes it possible to launch a DCC in that context, which we want to prevent. The same with folder creation for this asset.
Having an asset like a sequence is nice for grouping/parenting and would also help with syncing to Shotgun or CGWire.

**Comment by mottosso** [comment]
> But for us it makes sense to have assets (a sequence for example) without any task.

Ah, I think I understand.

It sounds like a useful property for these "meta assets" to have explicitly, rather than piggyback on whether or not they have an associated task. Would it make sense to enable these assets to be hidden or otherwise inaccessible from a GUI? E.g. `asset.data["hidden"] = True` or `asset.data["internal"] = True`?

**Comment by jasperges** [comment]
That might also be an option. But ideally I would like them to be visible in the UI and use a tree view or the traversing option from the [visual parenting PR](getavalon/core#38).
If you have a show with several episodes that contain around 20 sequences each consisting of hundreds of shots, choosing episode > sequence > shot is quite helpful. And (at least at the studio that hired me) artists like this.

**Comment by cameronpd** [comment]
Just thought I'd chime in, this will currently break the CGWire -> Avalon syncing scripts I'm working on, as I currently only sync Task Types at a project level. CGWire applies all Task Types to all assets/shots by default, so you have to remove a Task from a shot/asset if you don't want it to have one (as far as I know anyway). Not that this should stop this from happening, but just an example of something that will break with this change.

Also, as mentioned above the hidden setting for episodes and sequences can be used and this is what I currently do. Shots are grouped under their episodes and sequences in the loader and show under the visualparent folder display style in the manager etc, while episodes and sequences are not visible as assets.

**Comment by tokejepsen** [comment]
Explicitly assigning tasks to assets sounds good to me. Never liked the implicit nature of having project wide tasks.

@cameronpd have a look atbthe syncing script in the docker project. Had asset specific tasks working there.

**Comment by jasperges** [comment]
As mentioned [here](https://github.com/getavalon/launcher/pull/38#issuecomment-515499360), we now have [Allzpark](https://allzpark.com/). In the near future this should be able to replace this Launcher in production. Because of this I personally feel it's not worth spending more time on this. Closing...

**Pull request closed without merging**
