### PR TITLE
Get default application labels from toml files.

### PR DESCRIPTION
**Pull request by tokejepsen**
This PR will enable the launcher to query the labels of applications from their ```.toml``` files, to use as a default for the GUI.

### CODE REVIEW

**Comment by BigRoy** [comment]
Cool. Can you add a screenshot - I think the active Launcher in core is a bit behind from the one we currently use at Colorbleed. Here are two screenshots from ours:

afbeelding

afbeelding

Maybe it does something similar? :)

It also remains in the taskbar as an icon when closing (remembering previous window location and size when reopening it from taskbar)

**Comment by tokejepsen** [comment]
It is indeed behind! There are no actions in the current launcher.

film
shot01
animation

**Comment by tokejepsen** [comment]
Maybe we need a PR from Colorbleed to update the launcher?

**Comment by BigRoy** [comment]
Set up a PR from Colorbleed repo: https://github.com/getavalon/launcher/pull/27

Hopefully it also offers the functionality you're looking for here.

**Comment by tokejepsen** [comment]
It certainly will :)

**Pull request closed without merging**
